version: '3.8'

services:
  app:
    build:
      context: .
    container_name: aiqfome-api-app
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - aiqfome-network
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: aiqfome
      DB_USERNAME: postgres
      DB_PASSWORD: secret

  web:
    image: nginx:stable
    container_name: aiqfome-api-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - aiqfome-network

  db:
    image: postgres:15
    container_name: aiqfome-db
    environment:
      POSTGRES_DB: aiqfome
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - aiqfome-network

  pgsql-testing:
    image: postgres:16
    container_name: aiqfome-pgsql-testing
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: aiqfome_testing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - pgsql_testing_data:/var/lib/postgresql/data
    networks:
      - aiqfome-network

networks:
  aiqfome-network:

volumes:
  pgdata:
  pgsql_testing_data:
